### ISSUE TITLE
Question 6 not selectable

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/programming-univbasics-1-quiz#1]
Question 6 isn't formatted to be able to select an answer. The answer is backslash, I plan to advance to the next lesson for now even though the quiz "isn't complete."

**Comment by AudTheCodeWitch** [comment]
I am experiencing the same issue.

**Comment by thebkrasri** [comment]
I am also experiencing this issue

**Comment by hyosung11** [comment]
It still hasn't been fixed because I also have this issue.

**Comment by maxwellbenton** [comment]
Hello @PeteHanner, @MrsAud, @thebkrasri, and @hyosung11,

Thank you for spotting this and providing feedback! This has helped uncover a bug in our quiz interpretation system. We have updated this lesson and confirmed that all questions in this lesson are now selectable.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
