### ISSUE TITLE
Programming as Conversation: Expressions Quiz

### ISSUE THREAD

**Issue by CodingSensei19** [learn-co-curriculum/programming-univbasics-1-quiz#2]
The questions to the quiz were already answered, before I could take the quiz.

**Comment by sgharms** [comment]
I just tried this myself and saw:

![image](https://user-images.githubusercontent.com/50019/60814272-4ef4a180-a163-11e9-8ddc-2017dbcc7eaf.png)

The source material appears empty for my test account. I'll open a support ticket to see if we can track this down, but when I logged in as you, I saw the quiz and, as you pointed out, the answers were filled. thanks for letting us know.
